language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "christopheml-github"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
